// <auto-generated />
namespace NetMastery.Lab05.FileManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v102));
        
        string IMigrationMetadata.Id
        {
            get { return "201801172156510_v.1.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
