//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMastery.Lab05.FileManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLineNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMastery.Lab05.FileManager.CommandLineNames", typeof(CommandLineNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AddRoleCommand {
            get {
                return ResourceManager.GetString("AddRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd.
        /// </summary>
        internal static string ChangeDirectoryOption {
            get {
                return ResourceManager.GetString("ChangeDirectoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        internal static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -cr|--create &lt;value&gt;.
        /// </summary>
        internal static string CreateOption {
            get {
                return ResourceManager.GetString("CreateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createrole.
        /// </summary>
        internal static string CreateRoleCommand {
            get {
                return ResourceManager.GetString("CreateRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleterole.
        /// </summary>
        internal static string DeleteRoleCommand {
            get {
                return ResourceManager.GetString("DeleteRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory.
        /// </summary>
        internal static string DirectoryCommand {
            get {
                return ResourceManager.GetString("DirectoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -d|--download &lt;value&gt;.
        /// </summary>
        internal static string DownloadOption {
            get {
                return ResourceManager.GetString("DownloadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string FileCommand {
            get {
                return ResourceManager.GetString("FileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        internal static string getCommand {
            get {
                return ResourceManager.GetString("getCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -?|-h|--help.
        /// </summary>
        internal static string HelpOption {
            get {
                return ResourceManager.GetString("HelpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i|--info &lt;value&gt;.
        /// </summary>
        internal static string InfoOption {
            get {
                return ResourceManager.GetString("InfoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ls|--list &lt;value&gt;.
        /// </summary>
        internal static string ListOption {
            get {
                return ResourceManager.GetString("ListOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginCommand {
            get {
                return ResourceManager.GetString("LoginCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -l|--login &lt;value&gt;.
        /// </summary>
        internal static string LoginOption {
            get {
                return ResourceManager.GetString("LoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ls.
        /// </summary>
        internal static string LsCommand {
            get {
                return ResourceManager.GetString("LsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md.
        /// </summary>
        internal static string MdCommand {
            get {
                return ResourceManager.GetString("MdCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -mv|--move &lt;value&gt;.
        /// </summary>
        internal static string MoveOption {
            get {
                return ResourceManager.GetString("MoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p|--password &lt;value&gt;.
        /// </summary>
        internal static string PasswordOption {
            get {
                return ResourceManager.GetString("PasswordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        internal static string RdCommand {
            get {
                return ResourceManager.GetString("RdCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -rm|--remove &lt;value&gt;.
        /// </summary>
        internal static string RemoveOption {
            get {
                return ResourceManager.GetString("RemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveRoleCommand {
            get {
                return ResourceManager.GetString("RemoveRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -sr|--search &lt;value&gt;.
        /// </summary>
        internal static string SearchOption {
            get {
                return ResourceManager.GetString("SearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to singup.
        /// </summary>
        internal static string SingupCommand {
            get {
                return ResourceManager.GetString("SingupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u|--upload &lt;value&gt;.
        /// </summary>
        internal static string UploadOption {
            get {
                return ResourceManager.GetString("UploadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string UserCommand {
            get {
                return ResourceManager.GetString("UserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u | --user &lt;value&gt;.
        /// </summary>
        internal static string userOption {
            get {
                return ResourceManager.GetString("userOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whoami.
        /// </summary>
        internal static string WhoAmICommand {
            get {
                return ResourceManager.GetString("WhoAmICommand", resourceCulture);
            }
        }
    }
}
