//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMastery.FileManeger.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishLocalisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishLocalisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMastery.FileManeger.ConsoleApp.EnglishLocalisation", typeof(EnglishLocalisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoryCreateOptionNote {
            get {
                return ResourceManager.GetString("DirectoryCreateOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoryInfoOptionNote {
            get {
                return ResourceManager.GetString("DirectoryInfoOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoryListOptionNote {
            get {
                return ResourceManager.GetString("DirectoryListOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoryMoveOptionNote {
            get {
                return ResourceManager.GetString("DirectoryMoveOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoryRemoveOptionNote {
            get {
                return ResourceManager.GetString("DirectoryRemoveOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectorySearchOptionNote {
            get {
                return ResourceManager.GetString("DirectorySearchOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, password is incorrect.
        /// </summary>
        internal static string FailedAuthenticationNote {
            get {
                return ResourceManager.GetString("FailedAuthenticationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, trere is no user with login .
        /// </summary>
        internal static string FailedIdentificationNote {
            get {
                return ResourceManager.GetString("FailedIdentificationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi stranger. Please login for using this service..
        /// </summary>
        internal static string LoginNote {
            get {
                return ResourceManager.GetString("LoginNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login  is required.
        /// </summary>
        internal static string LoginOptionHelpNote {
            get {
                return ResourceManager.GetString("LoginOptionHelpNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordOptionHelpNote {
            get {
                return ResourceManager.GetString("PasswordOptionHelpNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creation date: .
        /// </summary>
        internal static string UserInfoCmdOutputCreationDate {
            get {
                return ResourceManager.GetString("UserInfoCmdOutputCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login: .
        /// </summary>
        internal static string UserInfoCmdOutputLogin {
            get {
                return ResourceManager.GetString("UserInfoCmdOutputLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storaged used: .
        /// </summary>
        internal static string UserInfoCmdOutputStorageSize {
            get {
                return ResourceManager.GetString("UserInfoCmdOutputStorageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, .
        /// </summary>
        internal static string WelcomeNote {
            get {
                return ResourceManager.GetString("WelcomeNote", resourceCulture);
            }
        }
    }
}
