//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMastery.Lab05.FileManager.UI.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLineNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMastery.Lab05.FileManager.UI.CommandLineApplicationCommands.CommandLineNames", typeof(CommandLineNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd.
        /// </summary>
        internal static string ChangeDirectoryCommand {
            get {
                return ResourceManager.GetString("ChangeDirectoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        internal static string CreateCommand {
            get {
                return ResourceManager.GetString("CreateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory.
        /// </summary>
        internal static string DirectoryCommand {
            get {
                return ResourceManager.GetString("DirectoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string DownloadCommand {
            get {
                return ResourceManager.GetString("DownloadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string ExitCommand {
            get {
                return ResourceManager.GetString("ExitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string FileCommand {
            get {
                return ResourceManager.GetString("FileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "-?|-h|--help".
        /// </summary>
        internal static string HelpOption {
            get {
                return ResourceManager.GetString("HelpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string InfoCommand {
            get {
                return ResourceManager.GetString("InfoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string ListCommand {
            get {
                return ResourceManager.GetString("ListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginCommand {
            get {
                return ResourceManager.GetString("LoginCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -l|--login &lt;value&gt;.
        /// </summary>
        internal static string LoginOption {
            get {
                return ResourceManager.GetString("LoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logoff.
        /// </summary>
        internal static string LogoffCommand {
            get {
                return ResourceManager.GetString("LogoffCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p|--password &lt;value&gt;.
        /// </summary>
        internal static string PasswordOption {
            get {
                return ResourceManager.GetString("PasswordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string RemoveCommand {
            get {
                return ResourceManager.GetString("RemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string SearchCommand {
            get {
                return ResourceManager.GetString("SearchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        internal static string UploadCommand {
            get {
                return ResourceManager.GetString("UploadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string UserCommand {
            get {
                return ResourceManager.GetString("UserCommand", resourceCulture);
            }
        }
    }
}
