// <auto-generated />
namespace NetMastery.InventoryManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v200));
        
        string IMigrationMetadata.Id
        {
            get { return "201801311247548_v.2.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
